baseurl = "https://mbren.github.io/"
title = "Programmer Writer Services"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
googleAnalytics = "UA-89052006-1"

# Define the number of posts per page
paginate = 10

[params]
    # viewMorePostLink     = "/blog/"
    # author = "mbren"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
        #email = "your@email.com"

#    about_us = "<p>todo</p>"
    # copyright = "Copyright (c) 2016"
    date_format = "2006-01-02"
    logo = "img/logo.png"
#    address =
#    """<p><strong>Universal Ltd.</strong>
#       <br>13/25 New Avenue
#        <br>Newtown upon River
#        <br>45Y 73J
#        <br>England
#        <br>
#        <strong>Great Britain</strong>
#      </p>
#      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[[params.menu]]
    name = "Services"
    url  = "/"
    weight = 1

# [[params.menu]]
#     name = "Blog"
#     url  = "/blog/"
#     weight = 2

# [[params.menu]]
#     name = "Contact"
#     url  = "/contact/"
#     weight = 4

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    # icon = "fa fa-file-code-o"
    icon = "fa fa-bullhorn"
    title = "Let's talk"
    subtitle = "To get more information about the services I offer, visit my LinkedIn profile."
    link_url = "https://www.linkedin.com/in/marybrennan"
    link_text = "Visit my LinkedIn profile"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From the blog"
    subtitle = ""
